### PR TITLE
More Sites

### PR DESCRIPTION
**Pull request by soleribbon**

### CODE REVIEW

**Comment by yourfavorite** [comment]
You shouldn't rename config.example.json imo. It is better to leave it separate so someone doesn't accidentally push their config.json file to the repo.

**Comment by soleribbon** [comment]
Got it thanks - more for personal use though- any ideas how to take the original shopify-monitor repo and duplicate it but also be able to add my own code and recieve his updates?

**Comment by soleribbon** [comment]
@yourfavorite

**Comment by yourfavorite** [comment]
You need to fork this repository so you have your own version of it. Then when he makes an update, you should create a new branch in your forked repo (in case his new code really messes up your updates). Pull from his repo and then fix any merge conflicts. When you are finished, checkout your master branch. Merge your other branch into your master branch and then push it up to your repo. From there you can create a pull request for Peter to take your code updates and put them into this main repo. Hopefully that makes sense.

**Comment by yourfavorite** [comment]
Hmm, actually looks like you committed your config.json which has your Slack auth info in it. You should definitely change your slack access token via slack.com and update it in your config file. And then in your .gitignore file, make sure config.json is listed if it isn't already.

**Comment by soleribbon** [comment]
Thanks, I think since I'm just a beginner on github and the terminology is still a bit unfamiliar to me I'll just check if he has updated it on his main repo on my main computer and if he has I'll fork the new version and edit the files from there.

**Pull request closed without merging**
